import React, { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import Button from '../components/Button'
import { Collapse } from 'react-bootstrap'

export default function Home() {

  const [on, setOn] = useState(false)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container p-4">
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="h4 text-center my-5">
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <Button onClick={() => setOn(!on)}>
          Read more...
        </Button>

        <Collapse in={on}><div> {/* this is to protect collapse */}
          <div className="row g-4 p-3">
            <div class="col-12">
              <Link href="/about">
                <a className="card">
                  <h2>About Page &rarr;</h2>
                  <p>Cypress will test if this link is working.</p>
                </a>
              </Link>
            </div>

            <div class="col-6">
              <a href="https://nextjs.org/docs" className="card">
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </div>

            <div class="col-6">
              <a href="https://nextjs.org/learn" className="card">
                <h2>Learn &rarr;</h2>
                <p>Learn about Next.js in an interactive course with quizzes!</p>
              </a>
            </div>

            <div class="col-6">
              <a
                href="https://github.com/vercel/next.js/tree/master/examples"
                className="card"
              >
                <h2>Examples &rarr;</h2>
                <p>Discover and deploy boilerplate example Next.js projects.</p>
              </a>
            </div>

            <div class="col-6">
              <a
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                className="card"
              >
                <h2>Deploy &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with Vercel.
                </p>
              </a>
            </div>
          </div>
        </div></Collapse>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
